language: node_js
node_js:
  - "10"
before_script:
  - npm install -g gatsby
script:
  - gatsby build
deploy:
  provider: firebase
  on:
    branch: master
  skip_cleanup: true
after_success:
  - firebase deploy --project dev-blog --token $FIREBASE_TOKEN