language: node_js
before_script:
  - npm install -g gatsby
node_js:
  - "10"
deploy:
  provider: firebase
  script: gatsby build
  skip_cleanup: true
  on:
    branch: master
after_success:
  - firebase deploy --project dev-blog --token $FIREBASE_TOKEN