language: node_js
node_js:
- '10'
before_script:
- npm install -g gatsby
script:
- gatsby build
deploy:
  provider: firebase
  on:
    branch: master
  skip_cleanup: true
after_success:
- firebase deploy --project dev-blog --token $FIREBASE_TOKEN
env:
  global:
  - secure: OfnpzA87WmhRR6PW1YnfgTnxhqHSCHzh9ucpmaWpB0chq5WGgGOrs/JBN51HiG6ZvmIfDujs9wcVQa0ag56E9moRHRnHgAGreSeQuUoUJFX8oNczsaoayyWBGJuHoXYHPctWu1n3N3huWIErCIZGvBuyZVoqfGfcSE/L1v9T/Q2oAk53VH4nsys3BfXKh+uAM60VpLCtOLeS4W/eCQrFzbidV79RFboJeHJQE7JFR7GFrZN5E2dCu3BOy9dzbxnU7tR6WWNWCuzPom8cbp+/5ergB0OMIy9AOARn3ePF8tjVteGj2QxymxsgAGp1gpI2z6DjBsVjvpTVUUXHtz2lNy0lBNToC8IfdhDVH3baHKIcGYIapESV9DAiWVwcYTf3aZW2KOFC/uMVWnxhMKell1Qrq16gUSxovJVeLj90gecgmuITKhVpomm1ysMs4ND+bkbeaVhlGaYb5VvWg5GiaU5QLo61Fu3ZyUkc1nMKBOCc5qgEvgrJmX5tQchEsIlqGSjiq73rrSP3wcyfowxb/OStZlyj46eK4ND/ojw/W8FhxME8VWNEQIoTLSaO1P+jmCIwQ+kq/7BhZZW9WRgZqHcekJjewerB1AswSBY7Lx77IZT7zmEV9UueBoMV2DPaJihgRSYC7QENE1jpbXXpjvGOHX4S9x5ICFBuKifGR2w=
  - secure: KDs4edZFUf4FCi92P3DcSOQNa3AdyI3XlAjKL2jxkBlVk8Vp/I5sJD0TS9c0MPaSSbfazSs29LtLKJctbhwRr90F7v5zwJZI2wedfsaFjaf7oL/mVo5tkJi3hymol0jfDLjrK/4ng4dzW+MDdyLUOF3So8wIOv9hmIAQF9f0HeFjHMM8PkjZ0yJDlphFFQwCk9VmLDnLccJ84OyiJztdpq+s8dE5j3MvHF6SMghVdXVCH/4hnKym9/Xm+1QMQhOrhu5J6cGoKK0pJVKPqIcuQeQN0aELB5sm9p04zWPXds12FyRKs+0oKMkWk+l3j6Y7Yt4E6xZ0EgjqiztWUmBu0+bm0iWqgr5e4ndRX9LeoTsp7iyxtxDm1v550s4yRoO9+lRumLxVug3PvEeYq3Y1ixH0hYSEd66Zzg6h8fr3lBrxAu9tDDpUWWsJb1GmBSXyk08rNFqYL2Yl2mEnaD9RXsOSBt58OXT+8Tva9PVHbyuGZ2O9S9XMqejyVig4uuHMv8KecAMFazthURxEEgfPxw4sP3sotfSzTjnWUDg5QTouSGIcqxdGgEhjYjzXOl81C4psigYf2B9vByzS0L7+HwbZw88kQS9wb4EXN7E/17ZMXKc/DXrQL9aITTKclbaWa6n4TGWrUgM923Co6MYoH//4mGKooiAuMex1WP/+E+o=
  - secure: SFBPRkG1Nsd/D64u6EF7xBi5s6nkuKtcwXl3KDae9TRvHIm1jeFzNkuna2TrDR3SOVs0QtxSPwawCWx6Xm+fKlruc/u0FZr2RHjWK2V98FWObFVd1ZudEJiZWMfsta6da57E0rhHOxBZlbyxA85TqAYOYZ+2EVTZi6f8wRwgv7y5epAmte5vnLHUtqVTS5SesXFhq3kh3FwNoK9oNGuYfXrJLu1YgizsnbL78ZjXWA3lbzG58nDn0cueUaDxd/P2HzGZangv3Uj5Ukhwv9hbfcrg7ZXvzO+sig9cgqMgqQ+MRV0mWYVznOp4zCMdkdETliKHtZI5Spk79NrEuhJ4vGWwnf0iF1vd64k0bb0pbw3IZgTyC/XWefF9y5Vdi18UqNXHhikXYY2172fVZiPL6GlSyiSUhWBnkl5cJhX3wXJnN4A0IXTkDv7hIoUryGsozwUROBeNQ/sOutQQr5HTHF2zu0UQxRjWDroPprlh2143GbvLOZfUZJn5kiMYyq5pxOuJ8bGxkqjYRSWIt6Qgmxty/16SpMCPrFAyhbWUu3at9Ti4F0yink6BTQAiDtRIxLQFaxG0a6/h7LPAKauAV+tMxDlcYgJssLyxpJwQ0wOys4u8ZGag54roh+phKf55VqJapfppOb0jv5LlP9bni6EevnGWeU2pjLJUsjO46Tw=
